//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Medico.Service.DynamicForm
{
	/// <summary>
	/// Database       : medico_formdb
	/// Data Source    : 192.168.0.10
	/// Server Version : 5.5.5-10.2.5-MariaDB
	/// </summary>
	public partial class MedicoBaseDb : LinqToDB.Data.DataConnection
	{
		public ITable<MsDynamicFormTemplates> MsDynamicFormTemplates { get { return this.GetTable<MsDynamicFormTemplates>(); } }
		public ITable<TrDynamicFormPatient>   TrDynamicFormPatient   { get { return this.GetTable<TrDynamicFormPatient>(); } }

		public MedicoBaseDb()
		{
			InitDataContext();
		}

		public MedicoBaseDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("ms_dynamic_form_templates")]
	public partial class MsDynamicFormTemplates
	{
		[Column(@"dynamic_form_template_id"),   PrimaryKey,  NotNull] public string    DynamicFormTemplateId   { get; set; } // varchar(36)
		[Column(@"tenant_id"),                     Nullable         ] public string    TenantId                { get; set; } // varchar(36)
		[Column(@"site_id"),                       Nullable         ] public string    SiteId                  { get; set; } // varchar(36)
		[Column(@"dynamic_form_template_name"),    Nullable         ] public string    DynamicFormTemplateName { get; set; } // varchar(100)
		[Column(@"template"),                      Nullable         ] public string    Template                { get; set; } // text
		[Column(@"add_date"),                      Nullable         ] public DateTime? AddDate                 { get; set; } // datetime
		[Column(@"add_by"),                        Nullable         ] public string    AddBy                   { get; set; } // varchar(36)
		[Column(@"edit_date"),                     Nullable         ] public DateTime? EditDate                { get; set; } // datetime
		[Column(@"edit_by"),                       Nullable         ] public string    EditBy                  { get; set; } // varchar(36)
		[Column(@"is_deleted"),                    Nullable         ] public ulong?    IsDeleted               { get; set; } // bit(1)
		[Column(@"is_active"),                     Nullable         ] public ulong?    IsActive                { get; set; } // bit(1)
	}

	[Table("tr_dynamic_form_patient")]
	public partial class TrDynamicFormPatient
	{
		[Column(@"tr_dynamic_form_patient_id"),  PrimaryKey,  NotNull] public string    TrDynamicFormPatientId  { get; set; } // varchar(36)
		[Column(@"ms_dynamic_form_template_id"),    Nullable         ] public string    MsDynamicFormTemplateId { get; set; } // varchar(36)
		[Column(@"patient_id"),                     Nullable         ] public string    PatientId               { get; set; } // varchar(36)
		[Column(@"tenant_id"),                      Nullable         ] public string    TenantId                { get; set; } // varchar(36)
		[Column(@"site_id"),                        Nullable         ] public string    SiteId                  { get; set; } // varchar(36)
		[Column(@"reference_id"),                   Nullable         ] public string    ReferenceId             { get; set; } // varchar(36)
		[Column(@"process_type"),                   Nullable         ] public string    ProcessType             { get; set; } // varchar(100)
		[Column(@"key"),                            Nullable         ] public string    Key                     { get; set; } // varchar(255)
		[Column(@"value"),                          Nullable         ] public string    Value                   { get; set; } // varchar(255)
		[Column(@"add_date"),                       Nullable         ] public DateTime? AddDate                 { get; set; } // datetime
		[Column(@"add_by"),                         Nullable         ] public string    AddBy                   { get; set; } // varchar(36)
		[Column(@"edit_date"),                      Nullable         ] public DateTime? EditDate                { get; set; } // datetime
		[Column(@"edit_by"),                        Nullable         ] public string    EditBy                  { get; set; } // varchar(36)
		[Column(@"is_deleted"),                     Nullable         ] public ulong?    IsDeleted               { get; set; } // bit(1)
		[Column(@"is_active"),                      Nullable         ] public ulong?    IsActive                { get; set; } // bit(1)
	}

	public static partial class TableExtensions
	{
		public static MsDynamicFormTemplates Find(this ITable<MsDynamicFormTemplates> table, string DynamicFormTemplateId)
		{
			return table.FirstOrDefault(t =>
				t.DynamicFormTemplateId == DynamicFormTemplateId);
		}

		public static TrDynamicFormPatient Find(this ITable<TrDynamicFormPatient> table, string TrDynamicFormPatientId)
		{
			return table.FirstOrDefault(t =>
				t.TrDynamicFormPatientId == TrDynamicFormPatientId);
		}
	}
}
